"use client";
import React, { useEffect, useState } from "react";
import {
  Minus,
  Plus,
  Trash2,
  ShoppingBag,
  ArrowLeft,
  Mail,
  User,
  MapPin,
  Phone,
} from "lucide-react";
import Link from "next/link";
import { createData, getById } from "@/lib/apiService";
import { ProductData } from "@/lib/types/product";
import { useCurrency } from "@/context/CurrencyContext";
import { usePromo } from "@/context/PromoContext";
import { calculateFinalPrice } from "@/lib/helpers/promo-helper";
import { useSession } from "next-auth/react";
import LoadingPage from "@/components/loading";
import {
  IShippingAddress,
  IOrderDetail,
  OrderData,
  OrderForm,
} from "@/lib/types/order";
import { showConfirmAlert, showErrorAlert } from "@/lib/helpers/sweetalert2";
import { useRouter } from "next/navigation";

export default function CartPage() {
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string>("");
  const { data: session, status } = useSession();
  const { activePromos, loading: promosLoading } = usePromo();

  const { currency, format } = useCurrency();

  const [formData, setFormData] = useState<OrderForm>({
    orderDate: new Date(),
    invoiceNumber: "", // Will be generated by backend
    totalAmount: 0,
    status: "pending confirmation" as
      | "pending confirmation"
      | "paid"
      | "processing"
      | "shipped",
    shippingAddress: {
      fullName: "",
      email: "",
      phone: "",
      country: "",
      city: "",
      district: "",
      zipCode: "",
      address: "",
    },
    shippingCost: 0,
    orderDetails: [] as IOrderDetail[],
    currency,
    orderType: session?.user.role === "reseller" ? "B2B" : "B2C",
  });

  const router = useRouter();

  const handleAddressChange = (
    field: keyof IShippingAddress,
    value: string
  ) => {
    setFormData((prev) => ({
      ...prev,
      shippingAddress: { ...prev.shippingAddress, [field]: value },
    }));
  };

  const isAddressValid = () => {
    return Object.values(formData.shippingAddress).every(
      (value) => value.trim() !== ""
    );
  };

  const updateQuantity = (id: string, newQuantity: number) => {
    if (newQuantity < 1) return;

    // First, update the quantity for the specific item
    const updatedWithNewQty = formData.orderDetails.map((item: any) => {
      if (item.variantId === id) {
        return { ...item, quantity: newQuantity };
      }
      return item;
    });

    // For B2B (reseller), we need to recalculate ALL items' discounts
    // because tier discounts depend on total category quantities
    // For B2C (retail), we can just recalculate the changed item
    const updated = updatedWithNewQty.map((item: any) => {
      const result = getDiscountedPrice(
        item.originalPrice[currency],
        item.quantity,
        item.productId,
        item.variantId,
        item.categoryId,
        updatedWithNewQty, // Pass updated cart items for accurate B2B calculation
        item.resellerPricing
      );

      return {
        ...item,
        discountPercentage: result.discountPercentage,
        discountedPrice: result.discountedPrice,
        subTotal: item.quantity * result.finalPrice,
      };
    });

    setFormData((prev) => ({
      ...prev,
      orderDetails: updated,
      totalAmount: updated.reduce((sum, el) => sum + el.subTotal, 0),
    }));

    const cartItem = JSON.parse(localStorage.getItem("cartItem") || "[]");
    localStorage.setItem(
      "cartItem",
      JSON.stringify(
        cartItem.map((c: any) =>
          c.variantId === id ? { ...c, quantity: newQuantity } : c
        )
      )
    );

    // Trigger event to update cart badge in header
    window.dispatchEvent(new Event("cartUpdated"));
  };

  const removeItem = (id: string) => {
    let filter = formData.orderDetails.filter((item) => item.variantId !== id);

    // For B2B (reseller), recalculate discounts for remaining items
    // since tier discounts depend on total category quantities
    // For B2C (retail), prices remain the same as they are per variant
    const recalculatedFilter = filter.map((item: any) => {
      const result = getDiscountedPrice(
        item.originalPrice[currency],
        item.quantity,
        item.productId,
        item.variantId,
        item.categoryId,
        filter, // Pass filtered cart items for accurate B2B calculation
        item.resellerPricing
      );

      return {
        ...item,
        discountPercentage: result.discountPercentage,
        discountedPrice: result.discountedPrice,
        subTotal: item.quantity * result.finalPrice,
      };
    });

    // update state
    setFormData((prev) => ({
      ...prev,
      orderDetails: recalculatedFilter,
      totalAmount: recalculatedFilter.reduce(
        (sum: number, element: any) => sum + element.subTotal,
        0
      ),
    }));

    // update localStorage
    let cartItem = JSON.parse(localStorage.getItem("cartItem") || "[]");

    let filterCartItem = cartItem.filter((item: any) => item.variantId !== id);

    localStorage.setItem("cartItem", JSON.stringify(filterCartItem));

    // Trigger event to update cart badge in header
    window.dispatchEvent(new Event("cartUpdated"));
  };

  const totalAmount = formData.orderDetails
    .filter((el) => el.quantity <= el.stock || el.preOrder.enabled)
    .reduce((sum, item) => sum + item.subTotal, 0);

  const hasOutOfStock =
    formData.orderDetails.filter(
      (el) => el.quantity > el.stock && !el.preOrder.enabled
    ).length !== 0;

  // Check MOQ per product for resellers
  const getMOQWarnings = () => {
    if (session?.user.role !== "reseller") return [];

    const warnings: Array<{
      productId: string;
      productName: string;
      moq: number;
      currentQty: number;
      needed: number;
    }> = [];

    // Group items by productId and sum quantities
    const productQuantities = formData.orderDetails.reduce(
      (acc, item) => {
        if (!acc[item.productId]) {
          acc[item.productId] = {
            productName: item.productName,
            moq: item.moq || 1,
            totalQty: 0,
          };
        }
        acc[item.productId].totalQty += item.quantity;
        return acc;
      },
      {} as Record<
        string,
        { productName: string; moq: number; totalQty: number }
      >
    );

    // Check each product against MOQ
    Object.entries(productQuantities).forEach(([productId, data]) => {
      if (data.moq > 1 && data.totalQty < data.moq) {
        warnings.push({
          productId,
          productName: data.productName,
          moq: data.moq,
          currentQty: data.totalQty,
          needed: data.moq - data.totalQty,
        });
      }
    });

    return warnings;
  };

  const moqWarnings = getMOQWarnings();

  const handleCheckout = async () => {
    // Check if user is logged in
    if (!session || status !== "authenticated") {
      const result = await showConfirmAlert(
        "You need to log in to complete your order. Would you like to log in now?",
        "Yes, Log In"
      );
      if (result.isConfirmed) {
        router.push("/login");
      }
      return;
    }

    if (hasOutOfStock) {
      showErrorAlert(
        undefined,
        "there are items that are not available (out of stock)"
      );
      return;
    }

    // Check MOQ for resellers
    if (moqWarnings.length > 0) {
      showErrorAlert(
        "MOQ Requirements Not Met",
        "Please add more items to meet the minimum order quantity requirements shown below."
      );
      return;
    }

    const result = await showConfirmAlert(
      "You want to continue checkout? Make sure all data is correct.",
      "Yes, Checkout Now"
    );

    if (!result.isConfirmed) return;

    try {
      let { data } = await createData<OrderData, OrderForm>(
        "/api/public/orders",
        formData
      );

      router.push(`/order-success/${data?._id}`);

      localStorage.removeItem("cartItem");

      // Trigger event to update cart badge in header
      window.dispatchEvent(new Event("cartUpdated"));
    } catch (error) {
      console.error(error);
      showConfirmAlert(
        "An error occurred during checkout. Please try again later.",
        "Ok"
      );
    }
  };

  const shipping = totalAmount > 50 ? 0 : 9.99;
  const total = totalAmount + shipping;

  // B2B: Calculate tier discount for a specific product based on total category quantities in cart
  const calculateB2BDiscount = (
    categoryId: string,
    currentCartItems: any[], // Pass cart items as parameter instead of relying on formData
    resellerPricing?: {
      currency: string;
      tiers: Array<{
        name: string;
        minimumQuantity: number;
        discount: number;
        categoryProduct: string | string[];
      }>;
    }
  ) => {
    if (
      !resellerPricing ||
      !resellerPricing.tiers ||
      !Array.isArray(resellerPricing.tiers)
    ) {
      return { discountPercentage: 0, tierName: null };
    }

    // Find all tiers that include this product's category
    const applicableTiers = resellerPricing.tiers.filter((tier) => {
      const categories = Array.isArray(tier.categoryProduct)
        ? tier.categoryProduct
        : [tier.categoryProduct];
      return categories.includes(categoryId);
    });

    if (applicableTiers.length === 0) {
      return { discountPercentage: 0, tierName: null };
    }

    // For each applicable tier, calculate total quantity of all products in that tier's categories
    let bestTier = null;
    let highestDiscount = 0;

    for (const tier of applicableTiers) {
      const categories = Array.isArray(tier.categoryProduct)
        ? tier.categoryProduct
        : [tier.categoryProduct];

      // Sum quantities of all products whose categoryId is in this tier's categories
      const totalCategoryQty = currentCartItems.reduce((sum, item: any) => {
        if (categories.includes(item.categoryId)) {
          return sum + item.quantity;
        }
        return sum;
      }, 0);

      console.log(
        `[B2B Discount] Category ${categoryId} | Tier: ${tier.name} | Min: ${tier.minimumQuantity} | Total Category Qty: ${totalCategoryQty} | Discount: ${tier.discount}%`
      );

      // Check if this tier is qualified and has higher discount
      if (
        totalCategoryQty >= tier.minimumQuantity &&
        tier.discount > highestDiscount
      ) {
        highestDiscount = tier.discount;
        bestTier = tier;
      }
    }

    if (bestTier) {
      console.log(
        `[B2B Discount] Category ${categoryId} => Selected Tier: ${bestTier.name} | Discount: ${bestTier.discount}%`
      );
      return {
        discountPercentage: bestTier.discount,
        tierName: bestTier.name,
      };
    }

    return { discountPercentage: 0, tierName: null };
  };

  // B2C: Calculate promo discount for retail customers (per variant)
  const calculateB2CDiscount = (
    basePrice: number,
    productId: string,
    variantId: string
  ) => {
    const promoResult = calculateFinalPrice(
      basePrice,
      currency,
      productId,
      variantId,
      activePromos,
      false
    );

    if (promoResult.hasDiscount) {
      return {
        discountPercentage: promoResult.discountPercentage,
        finalPrice: promoResult.finalPrice,
      };
    }

    return {
      discountPercentage: 0,
      finalPrice: basePrice,
    };
  };

  // Universal Discount Calculator (B2C & B2B)
  const getDiscountedPrice = (
    basePrice: number,
    quantity: number,
    productId: string,
    variantId: string,
    categoryId: string,
    currentCartItems: any[], // Pass current cart items for B2B calculation
    resellerPricing?: any
  ) => {
    let discountPercentage = 0;
    let finalPrice = basePrice;

    if (session?.user.role === "reseller" && resellerPricing) {
      // B2B: Use tier-based discount calculation based on total category quantities
      const tierResult = calculateB2BDiscount(
        categoryId,
        currentCartItems,
        resellerPricing
      );

      if (tierResult.discountPercentage > 0) {
        discountPercentage = tierResult.discountPercentage;
        finalPrice = Math.round(
          basePrice - (basePrice * discountPercentage) / 100
        );
      }
    } else {
      // B2C: Use promo-based discount calculation per variant
      const promoResult = calculateB2CDiscount(basePrice, productId, variantId);
      discountPercentage = promoResult.discountPercentage;
      finalPrice = promoResult.finalPrice;
    }

    return {
      finalPrice,
      discountPercentage,
      discountedPrice:
        discountPercentage > 0 ? { [currency]: finalPrice } : null,
    };
  };

  const fetchCartItem = async () => {
    setIsLoading(true);
    try {
      const cartItem = JSON.parse(localStorage.getItem("cartItem") || "[]");

      // Debug log to verify promos are loaded
      console.log("Fetching cart with activePromos:", activePromos.length);

      // First pass: fetch all product data without calculating discounts
      const cartItemsWithoutDiscount = await Promise.all(
        cartItem.map(async (el: any) => {
          const { data } = await getById<ProductData>(
            "/api/public/products",
            el.productId
          );

          const variant = data?.productVariantsData?.find(
            (v) => v._id === el.variantId
          );

          if (data && variant) {
            return {
              productId: data._id,
              productName: data.productName,
              categoryId: data.categoryId,
              variantId: el.variantId,
              variantName: variant.name,
              originalPrice: variant.price,
              quantity: el.quantity,
              image:
                variant.image ||
                data.productMedia.find((m) => m.type === "image"),
              stock: variant.stock,
              preOrder: data.preOrder,
              moq: data.moq,
              resellerPricing: data.resellerPricing,
            };
          }
          return null;
        })
      );

      // Filter out null values
      const validCartItems = cartItemsWithoutDiscount.filter(
        (item) => item !== null
      );

      // Second pass: calculate discounts with complete cart data
      const detailCartItem = validCartItems.map((item: any) => {
        const basePrice = item.originalPrice[currency];

        const result = getDiscountedPrice(
          basePrice,
          item.quantity,
          item.productId,
          item.variantId,
          item.categoryId,
          validCartItems, // Pass complete cart items for B2B tier calculation
          item.resellerPricing
        );

        return {
          ...item,
          discountedPrice: result.discountedPrice,
          discountPercentage: result.discountPercentage,
          subTotal: item.quantity * result.finalPrice,
        };
      });

      setFormData((prev) => ({
        ...prev,
        orderDetails: detailCartItem,
        totalAmount: detailCartItem.reduce((sum, el) => sum + el.subTotal, 0),
      }));
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    // Only fetch cart items when session is loaded AND promos are loaded
    if (status !== "loading" && !promosLoading) {
      fetchCartItem();
    } else {
      // Keep loading state true while waiting for session or promos
      setIsLoading(true);
    }
  }, [currency, status, promosLoading, activePromos]);

  // Show loading while session or promos are loading
  if (isLoading || promosLoading) {
    return <LoadingPage />;
  }

  if (!isLoading && formData.orderDetails.length === 0) {
    return (
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-20">
        <div className="text-center">
          <div className="bg-gradient-to-r from-orange-400 to-rose-400 p-6 sm:p-8 rounded-full inline-flex mb-6 sm:mb-8">
            <ShoppingBag className="h-12 w-12 sm:h-16 sm:w-16 text-white" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-800 mb-3 sm:mb-4">
            Your Cart is Empty
          </h1>
          <p className="text-gray-600 mb-6 sm:mb-8 px-4">
            Looks like you haven't added any items to your cart yet.
          </p>
          <Link
            href="/catalog"
            className="inline-flex items-center px-4 sm:px-6 py-2 sm:py-3 bg-gradient-to-r from-orange-400 to-rose-400 text-white font-semibold rounded-lg hover:shadow-lg transform hover:scale-105 transition-all duration-200"
          >
            <ArrowLeft className="h-4 w-4 sm:h-5 sm:w-5 mr-2" />
            Continue Shopping
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-secondary min-h-screen">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 lg:gap-8">
          {/* Cart Items */}
          <div className="lg:col-span-2 space-y-6 lg:space-y-8">
            {/* MOQ Warnings for Resellers */}
            {moqWarnings.length > 0 && (
              <div className="max-w-full  mx-auto">
                <div className="bg-amber-50 border-2 border-amber-300 rounded-xl overflow-hidden">
                  <div className="p-3 md:p-4 lg:p-5">
                    <div className="space-x-3">
                      <div className="flex gap-3">
                        <div className="w-6 h-6 bg-amber-500 rounded-full flex items-center justify-center mt-0.5">
                          <span className="text-white text-sm font-bold">
                            !
                          </span>
                        </div>
                        <h3 className="text-base md:text-lg font-semibold text-amber-900 mb-2">
                          Minimum Order Quantity (MOQ) Not Met
                        </h3>
                      </div>

                      <p className="text-sm text-amber-800 mb-4 md:mb-5">
                        The following products require minimum order quantities.
                        Please add more items to proceed with checkout.
                      </p>

                      {/* List Item */}
                      <div className="space-y-3">
                        {moqWarnings.map((warning) => (
                          <div
                            key={warning.productId}
                            className="bg-white border border-amber-200 rounded-lg p-4"
                          >
                            <div className="flex items-start justify-between">
                              <div className="flex-1 min-w-0 pr-3">
                                <h4 className="font-semibold text-gray-900 text-base mb-1 truncate">
                                  {warning.productName}
                                </h4>
                                <div className="text-sm text-gray-600">
                                  <span className="font-medium">
                                    Current quantity in cart:
                                  </span>{" "}
                                  {warning.currentQty} pcs
                                </div>
                                <div className="text-sm text-gray-600">
                                  <span className="font-medium">
                                    Minimum required (MOQ):
                                  </span>{" "}
                                  {warning.moq} pcs
                                </div>
                              </div>

                              <div className="ml-2 flex-shrink-0">
                                <div className="bg-amber-100 border border-amber-300 rounded-lg px-3 py-3 text-center">
                                  <div className="text-xs text-amber-700 font-medium leading-none mb-1">
                                    Add More
                                  </div>
                                  <div className="text-xl font-bold text-amber-900 leading-none">
                                    +{warning.needed}
                                  </div>
                                  <div className="text-xs text-amber-700 leading-none mt-1">
                                    pcs needed
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Cart Items Section */}
            <div className="bg-white rounded-xl lg:rounded-2xl shadow-sm border border-primary/30 overflow-hidden">
              <div className="p-4 md:p-6">
                <div className="flex items-center space-x-3 mb-2">
                  <ShoppingBag className="w-6 h-6 text-primary" />
                  <h2 className="text-xl font-semibold text-gray-800">
                    Cart Items
                  </h2>
                </div>

                <div className="divide-y divide-gray-200">
                  {formData.orderDetails.map((item: any) => (
                    <div key={item.variantId} className="py-4">
                      {/* Desktop Cart Item - Full size for >= 750px */}
                      <div className="hidden min-[750px]:flex items-start space-x-4">
                        <div className="relative w-30 h-30">
                          <img
                            src={item.image?.imageUrl}
                            alt={item.name}
                            className={`w-30 h-30 object-cover rounded-lg ${
                              item.quantity > item.stock &&
                              !item.preOrder.enabled
                                ? "opacity-50 grayscale"
                                : ""
                            }`}
                          />

                          {item.quantity > item.stock &&
                            !item.preOrder.enabled && (
                              <div className="absolute inset-0 bg-black/50 rounded-lg flex items-center justify-center">
                                <span className="text-white text-sm font-bold">
                                  Out of Stock
                                </span>
                              </div>
                            )}
                        </div>

                        <div className="flex-1 min-w-0">
                          <h3 className="text-lg font-semibold text-gray-800 mb-1">
                            {item.productName}
                          </h3>
                          <div className="flex items-center space-x-4 text-sm text-gray-600 mb-2">
                            Variant: {item.variantName}
                          </div>

                          {item.quantity > item.stock &&
                            item.preOrder.enabled && (
                              <div className="text-amber-500 text-sm font-medium">
                                Pre-Order
                              </div>
                            )}

                          <div className="flex items-center justify-between">
                            <div className="flex flex-col space-y-1">
                              {item.discountedPrice ? (
                                <>
                                  <div className="flex items-center space-x-2">
                                    <span className="text-lg font-bold text-orange-600">
                                      {format(item.discountedPrice[currency])}
                                    </span>
                                    <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full font-semibold">
                                      -{item.discountPercentage}%
                                    </span>
                                  </div>
                                  <span className="text-sm text-gray-500 line-through">
                                    {format(item.originalPrice[currency])}
                                  </span>
                                </>
                              ) : (
                                <span className="text-lg font-bold text-gray-800">
                                  {format(item.originalPrice[currency])}
                                </span>
                              )}
                            </div>

                            <div className="flex items-center space-x-3">
                              <div className="flex items-center border border-gray-300 rounded-lg">
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity - 1
                                    )
                                  }
                                  className="p-2 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={item.quantity <= 1}
                                >
                                  <Minus className="h-4 w-4" />
                                </button>
                                <input
                                  type="text"
                                  value={item.quantity}
                                  onChange={(e) => {
                                    const value = parseInt(e.target.value);

                                    if (isNaN(value) || value <= 0) {
                                      updateQuantity(item.variantId, 1);
                                    } else {
                                      updateQuantity(item.variantId, value);
                                    }
                                  }}
                                  className="w-16 px-2 py-2 text-center font-medium border-0 focus:outline-none focus:ring-0"
                                  min={1}
                                />
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity + 1
                                    )
                                  }
                                  className="p-2 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={
                                    item.quantity > item.stock &&
                                    !item.preOrder.enabled
                                  }
                                >
                                  <Plus className="h-4 w-4" />
                                </button>
                              </div>

                              <button
                                onClick={() => removeItem(item.variantId)}
                                className="p-2 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors"
                              >
                                <Trash2 className="h-5 w-5" />
                              </button>
                            </div>
                          </div>
                          <div className="flex justify-between items-center mt-3 pt-2 border-t border-gray-100">
                            <span className="text-sm font-semibold text-gray-700">
                              Subtotal
                            </span>
                            <span className="text-lg font-bold text-primary">
                              {format(item.subTotal)}
                            </span>
                          </div>
                        </div>
                      </div>

                      {/* Compact Desktop Cart Item - For >= 490px && < 750px */}
                      <div className="hidden min-[490px]:max-[750px]:flex items-start space-x-3">
                        <div className="relative w-25 h-25">
                          <img
                            src={item.image?.imageUrl}
                            alt={item.name}
                            className={`w-25 h-25 object-cover rounded-lg ${
                              item.quantity > item.stock &&
                              !item.preOrder.enabled
                                ? "opacity-50 grayscale"
                                : ""
                            }`}
                          />

                          {item.quantity > item.stock &&
                            !item.preOrder.enabled && (
                              <div className="absolute inset-0 bg-black/50 rounded-lg flex items-center justify-center">
                                <span className="text-white text-sm font-bold">
                                  Out of Stock
                                </span>
                              </div>
                            )}
                        </div>

                        <div className="flex-1 min-w-0">
                          <h3 className="text-base font-semibold text-gray-800 mb-1">
                            {item.productName}
                          </h3>
                          <div className="flex items-center space-x-3 text-xs text-gray-600 mb-2">
                            Variant: {item.variantName}
                          </div>

                          {item.quantity > item.stock &&
                            item.preOrder.enabled && (
                              <div className="text-amber-500 text-xs font-medium">
                                Pre-order
                              </div>
                            )}

                          <div className="flex items-center justify-between">
                            <div className="flex flex-col space-y-0.5">
                              {item.discountedPrice ? (
                                <>
                                  <div className="flex items-center space-x-1.5">
                                    <span className="text-base font-bold text-orange-600">
                                      {format(item.discountedPrice[currency])}
                                    </span>
                                    <span className="text-[10px] bg-green-100 text-green-700 px-1.5 py-0.5 rounded-full font-semibold">
                                      -{item.discountPercentage}%
                                    </span>
                                  </div>
                                  <span className="text-xs text-gray-500 line-through">
                                    {format(item.originalPrice[currency])}
                                  </span>
                                </>
                              ) : (
                                <span className="text-base font-bold text-gray-800">
                                  {format(item.originalPrice[currency])}
                                </span>
                              )}
                            </div>

                            <div className="flex items-center space-x-2">
                              <div className="flex items-center border border-gray-300 rounded-md">
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity - 1
                                    )
                                  }
                                  className="p-1 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={item.quantity <= 1}
                                >
                                  <Minus className="h-3 w-3" />
                                </button>
                                <input
                                  type="text"
                                  value={item.quantity}
                                  onChange={(e) => {
                                    const value = parseInt(e.target.value);

                                    if (isNaN(value) || value <= 0) {
                                      updateQuantity(item.variantId, 1);
                                    } else {
                                      updateQuantity(item.variantId, value);
                                    }
                                  }}
                                  className="w-14 px-2 py-1 text-center font-medium text-sm border-0 focus:outline-none focus:ring-0"
                                  min={1}
                                />
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity + 1
                                    )
                                  }
                                  className="p-1 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={
                                    item.quantity > item.stock &&
                                    !item.preOrder.enabled
                                  }
                                >
                                  <Plus className="h-3 w-3" />
                                </button>
                              </div>

                              <button
                                onClick={() => removeItem(item.variantId)}
                                className="p-1 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-md transition-colors"
                              >
                                <Trash2 className="h-4 w-4" />
                              </button>
                            </div>
                          </div>

                          <div className="flex justify-between items-center mt-3 pt-2 border-t border-gray-100">
                            <span className="text-sm font-semibold text-gray-700">
                              Subtotal
                            </span>
                            <span className="text-base font-bold text-primary">
                              {format(item.subTotal)}
                            </span>
                          </div>
                        </div>
                      </div>

                      {/* Mobile Cart Item - Only show on screens <= 489px */}
                      <div className="block min-[490px]:hidden">
                        <div className="flex gap-3">
                          {/* Product Image */}
                          <div className="relative w-25 h-25 flex-shrink-0">
                            <img
                              src={item.image?.imageUrl}
                              alt={item.name}
                              className={`w-25 h-25 object-cover rounded-lg ${
                                item.quantity > item.stock &&
                                !item.preOrder.enabled
                                  ? "opacity-50 grayscale"
                                  : ""
                              }`}
                            />

                            {item.quantity > item.stock &&
                              !item.preOrder.enabled && (
                                <div className="absolute inset-0 bg-black/50 rounded-lg flex items-center justify-center">
                                  <span className="text-white text-sm font-bold">
                                    Out of Stock
                                  </span>
                                </div>
                              )}
                          </div>

                          {/* Product Info */}
                          <div className="flex-1 min-w-0 space-y-1">
                            {/* Product Name with overflow hidden */}
                            <h3 className="text-sm font-semibold text-gray-800 truncate">
                              {item.productName}
                            </h3>

                            {/* Variant Name with overflow hidden and smaller text */}
                            <div className="text-xs text-gray-600 truncate">
                              Variant: {item.variantName}
                            </div>

                            {/* Stock Status */}
                            {item.quantity > item.stock &&
                              item.preOrder.enabled && (
                                <span className="text-xs text-amber-500 font-medium">
                                  Pre-order
                                </span>
                              )}

                            {/* Price */}
                            <div className="flex flex-col space-y-0.5">
                              {item.discountedPrice ? (
                                <>
                                  <div className="flex items-center space-x-1.5">
                                    <span className="text-sm font-bold text-orange-600">
                                      {format(item.discountedPrice[currency])}
                                    </span>
                                    <span className="text-[9px] bg-green-100 text-green-700 px-1.5 py-0.5 rounded-full font-semibold">
                                      -{item.discountPercentage}%
                                    </span>
                                  </div>
                                  <span className="text-xs text-gray-500 line-through">
                                    {format(item.originalPrice[currency])}
                                  </span>
                                </>
                              ) : (
                                <span className="text-sm font-bold text-gray-800">
                                  {format(item.originalPrice[currency])}
                                </span>
                              )}
                            </div>

                            <div className="flex items-center space-x-2">
                              <span className="text-xs font-semibold text-gray-700">
                                Subtotal:
                              </span>
                              <span className="text-sm font-bold text-primary">
                                {format(item.subTotal)}
                              </span>
                            </div>

                            {/* Bottom Row: Quantity Controls and Delete Button */}
                            <div className="flex items-center justify-between pt-1">
                              <div className="flex items-center border border-gray-300 rounded-lg">
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity - 1
                                    )
                                  }
                                  className="p-1.5 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={item.quantity <= 1}
                                >
                                  <Minus className="h-3 w-3" />
                                </button>
                                <input
                                  type="text"
                                  value={item.quantity}
                                  onChange={(e) => {
                                    const value = parseInt(e.target.value);

                                    if (isNaN(value) || value <= 0) {
                                      updateQuantity(item.variantId, 1);
                                    } else {
                                      updateQuantity(item.variantId, value);
                                    }
                                  }}
                                  className="w-12 px-2 py-1.5 text-center font-medium text-sm border-0 focus:outline-none focus:ring-0"
                                  min={1}
                                />
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity + 1
                                    )
                                  }
                                  className="p-1.5 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={
                                    item.quantity > item.stock &&
                                    !item.preOrder.enabled
                                  }
                                >
                                  <Plus className="h-3 w-3" />
                                </button>
                              </div>

                              <button
                                onClick={() => removeItem(item.variantId)}
                                className="p-1.5 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors"
                              >
                                <Trash2 className="h-4 w-4" />
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Shipping Address Section */}
            <div className="bg-white rounded-xl lg:rounded-2xl shadow-sm border border-primary/30">
              <div className="p-4 sm:p-6">
                <div className="flex items-center space-x-3 mb-6">
                  <MapPin className="w-6 h-6 text-primary" />
                  <h2 className="text-xl font-semibold text-gray-800">
                    Shipping Address
                  </h2>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="sm:col-span-2">
                    <div>
                      <label className="flex items-center space-x-2 text-sm font-medium text-gray-700 mb-2">
                        <User className="w-4 h-4" />
                        <span>Full Name</span>
                      </label>
                      <input
                        type="text"
                        value={formData.shippingAddress.fullName}
                        onChange={(e) =>
                          handleAddressChange("fullName", e.target.value)
                        }
                        className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                        placeholder="Enter your full name"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="flex items-center space-x-2 text-sm font-medium text-gray-700 mb-2">
                      <Mail className="w-4 h-4" />
                      <span>Email Address</span>
                    </label>
                    <input
                      type="email"
                      value={formData.shippingAddress.email}
                      onChange={(e) =>
                        handleAddressChange("email", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter your email"
                    />
                  </div>

                  <div>
                    <label className="flex items-center space-x-2 text-sm font-medium text-gray-700 mb-2">
                      <Phone className="w-4 h-4" />
                      <span>Phone Number</span>
                    </label>
                    <input
                      type="tel"
                      value={formData.shippingAddress.phone}
                      onChange={(e) =>
                        handleAddressChange("phone", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter your phone number"
                    />
                  </div>

                  <div>
                    <label className="flex items-center text-sm font-medium text-gray-700 mb-2">
                      <span>Country</span>
                    </label>
                    <input
                      type="text"
                      value={formData.shippingAddress.country}
                      onChange={(e) =>
                        handleAddressChange("country", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter your country"
                    />
                  </div>

                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      City
                    </label>
                    <input
                      type="text"
                      value={formData.shippingAddress.city}
                      onChange={(e) =>
                        handleAddressChange("city", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter your city"
                    />
                  </div>

                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      District
                    </label>
                    <input
                      type="text"
                      value={formData.shippingAddress.district}
                      onChange={(e) =>
                        handleAddressChange("district", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter district"
                    />
                  </div>

                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Zip Code
                    </label>
                    <input
                      type="text"
                      value={formData.shippingAddress.zipCode}
                      onChange={(e) =>
                        handleAddressChange("zipCode", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter zip code"
                    />
                  </div>

                  <div className="sm:col-span-2">
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Street Address
                    </label>
                    <textarea
                      value={formData.shippingAddress.address}
                      onChange={(e) =>
                        handleAddressChange("address", e.target.value)
                      }
                      rows={3}
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors resize-none"
                      placeholder="Enter your complete address"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Order Summary */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-xl lg:rounded-2xl shadow-sm border border-primary/30 lg:sticky lg:top-30">
              <div className="p-4 sm:p-6">
                <h2 className="text-xl font-semibold text-gray-800 mb-6">
                  Order Summary
                </h2>

                <div className="space-y-4 mb-6">
                  <div className="flex justify-between text-gray-600">
                    <span>Subtotal</span>
                    <span>{format(totalAmount)}</span>
                  </div>

                  <div className="flex justify-between text-gray-600">
                    <span>Shipping</span>
                    <span>{format(shipping)}</span>
                  </div>

                  <div className="border-t border-gray-200 pt-4">
                    <div className="flex justify-between text-lg font-semibold text-gray-800">
                      <span>Total</span>
                      {format(total)}
                    </div>
                  </div>
                </div>

                <div className="space-y-2">
                  <button
                    className={`w-full font-semibold py-4 px-6 rounded-xl transition-all duration-200 shadow-lg ${
                      formData.orderDetails.length === 0 ||
                      !isAddressValid() ||
                      moqWarnings.length > 0
                        ? "bg-gray-300 text-gray-500 cursor-not-allowed"
                        : "bg-primary/90 hover:bg-primary text-white transform hover:scale-105 cursor-pointer"
                    }`}
                    disabled={
                      formData.orderDetails.length === 0 ||
                      !isAddressValid() ||
                      moqWarnings.length > 0
                    }
                    onClick={handleCheckout}
                  >
                    {moqWarnings.length > 0
                      ? "MOQ Requirements Not Met"
                      : !isAddressValid()
                        ? "Complete Address to Continue"
                        : "Confirm Order via Whatsapp"}
                  </button>
                  {isAddressValid() && moqWarnings.length === 0 && (
                    <small>
                      <span className="text-red-500">* note:</span> you will be
                      directed to Whatsapp for secure and faster order
                      confirmation
                    </small>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
