"use client";
import React, { useEffect, useState } from "react";
import {
  Minus,
  Plus,
  Trash2,
  ShoppingBag,
  ArrowLeft,
  Mail,
  User,
  MapPin,
  Phone,
} from "lucide-react";
import Link from "next/link";
import { createData, getById } from "@/lib/apiService";
import { ProductData } from "@/lib/types/product";
import { useCurrency } from "@/context/CurrencyContext";
import { useSession } from "next-auth/react";
import LoadingPage from "@/components/loading";
import {
  IShippingAddress,
  IOrderDetail,
  OrderData,
  OrderForm,
} from "@/lib/types/order";
import { showConfirmAlert } from "@/lib/helpers/sweetalert2";
import { useRouter } from "next/navigation";

export default function CartPage() {
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string>("");
  const { data: session, status } = useSession();

  const { currency, format } = useCurrency();

  const [formData, setFormData] = useState<OrderForm>({
    orderDate: new Date(),
    invoiceNumber: "", // Will be generated by backend
    totalAmount: 0,
    status: "pending confirmation" as
      | "pending confirmation"
      | "paid"
      | "processing"
      | "shipped",
    shippingAddress: {
      fullName: "",
      email: "",
      phone: "",
      country: "",
      city: "",
      district: "",
      zipCode: "",
      address: "",
    },
    shippingCost: 0,
    orderDetails: [] as IOrderDetail[],
    currency,
    orderType: session?.user.role === "reseller" ? "B2B" : "B2C",
  });

  const router = useRouter();

  const handleAddressChange = (
    field: keyof IShippingAddress,
    value: string
  ) => {
    setFormData((prev) => ({
      ...prev,
      shippingAddress: { ...prev.shippingAddress, [field]: value },
    }));
  };

  const isAddressValid = () => {
    return Object.values(formData.shippingAddress).every(
      (value) => value.trim() !== ""
    );
  };

  const updateQuantity = (id: string, newQuantity: number) => {
    if (newQuantity < 1) return;

    let findProduct = formData.orderDetails.find((el) => el.variantId === id);

    if (!findProduct) {
      return;
    }

    // update state setCartItemData
    const updatedCartItemData = formData.orderDetails.map((item) => {
      if (item.variantId === id) {
        // Recalculate discount for new quantity
        const basePrice = item.originalPrice[currency];
        let finalPrice = basePrice;
        let discountInfo: {
          discountPercentage: number;
          tierName: string | null;
        } = {
          discountPercentage: 0,
          tierName: null,
        };

        // Calculate reseller discount if applicable
        if (session?.user.role === "reseller" && item.resellerPricing) {
          discountInfo = calculateResellerDiscount(
            newQuantity,
            item.resellerPricing
          );

          if (discountInfo.discountPercentage > 0) {
            const discountAmount =
              (basePrice * discountInfo.discountPercentage) / 100;
            finalPrice = Math.round(basePrice - discountAmount);
          }
        }

        // TODO: Add B2C discount calculation here in the future

        return {
          ...item,
          quantity: newQuantity,
          discountPercentage: discountInfo.discountPercentage,
          discountedPrice:
            discountInfo.discountPercentage > 0
              ? { [currency]: finalPrice }
              : null,
          subTotal: newQuantity * finalPrice,
        };
      }
      return item;
    });

    setFormData((prev) => ({
      ...prev,
      orderDetails: updatedCartItemData,
      totalAmount: updatedCartItemData.reduce(
        (sum: number, element: any) => sum + element.subTotal,
        0
      ),
    }));

    // update localStorage
    let cartItem = JSON.parse(localStorage.getItem("cartItem") || "[]");

    let updatedCartItem = cartItem.map((el: any) => {
      if (el.variantId === id) {
        el.quantity = newQuantity;
      }

      return el;
    });

    localStorage.setItem("cartItem", JSON.stringify(updatedCartItem));
  };

  const removeItem = (id: string) => {
    let filter = formData.orderDetails.filter((item) => item.variantId !== id);

    // update state
    setFormData((prev) => ({
      ...prev,
      orderDetails: filter,
      totalAmount: filter.reduce(
        (sum: number, element: any) => sum + element.subTotal,
        0
      ),
    }));

    // update localStorage
    let cartItem = JSON.parse(localStorage.getItem("cartItem") || "[]");

    let filterCartItem = cartItem.filter((item: any) => item.variantId !== id);

    localStorage.setItem("cartItem", JSON.stringify(filterCartItem));
  };

  const totalAmount = formData.orderDetails.reduce(
    (sum, item) => sum + item.subTotal,
    0
  );

  const handleCheckout = async () => {
    const result = await showConfirmAlert(
      "You want to continue checkout? Make sure all data is correct.",
      "Yes, Checkout Now"
    );

    if (!result.isConfirmed) return;

    try {
      let { data } = await createData<OrderData, OrderForm>(
        "/api/public/orders",
        formData
      );

      router.push(`/order-success/${data?._id}`);

      localStorage.removeItem("cartItem");
    } catch (error) {
      console.error(error);
      showConfirmAlert(
        "An error occurred during checkout. Please try again later.",
        "Ok"
      );
    }
  };

  const shipping = totalAmount > 50 ? 0 : 9.99;
  const total = totalAmount + shipping;

  // Helper function to calculate reseller discount
  const calculateResellerDiscount = (
    quantity: number,
    resellerPricing?: {
      currency: string;
      tiers: Array<{
        name: string;
        minimumQuantity: number;
        discount: number;
        categoryProduct: string | string[];
      }>;
    }
  ) => {
    if (!resellerPricing || !resellerPricing.tiers) {
      return { discountPercentage: 0, tierName: null };
    }

    // Find the highest applicable tier based on quantity
    let applicableTier = null;
    for (const tier of resellerPricing.tiers) {
      if (quantity >= tier.minimumQuantity) {
        if (
          !applicableTier ||
          tier.minimumQuantity > applicableTier.minimumQuantity
        ) {
          applicableTier = tier;
        }
      }
    }

    if (applicableTier) {
      return {
        discountPercentage: applicableTier.discount,
        tierName: applicableTier.name,
      };
    }

    return { discountPercentage: 0, tierName: null };
  };

  const fetchCartItem = async () => {
    setIsLoading(true);
    try {
      let cartItem = JSON.parse(localStorage.getItem("cartItem") || "[]");

      const detailCartItem = await Promise.all(
        cartItem.map(async (el: any) => {
          const { data: product } = await getById<ProductData>(
            "/api/public/products",
            el.productId
          );

          let variant = product?.productVariantsData?.find(
            (item) => item._id === el.variantId
          );

          const basePrice = variant?.price[currency] || 0;

          // Calculate discount (for both B2B reseller and B2C customer)
          let discountInfo: {
            discountPercentage: number;
            tierName: string | null;
          } = {
            discountPercentage: 0,
            tierName: null,
          };
          let finalPrice = basePrice;

          // Calculate reseller discount if applicable
          if (session?.user.role === "reseller" && product?.resellerPricing) {
            discountInfo = calculateResellerDiscount(
              el.quantity,
              product.resellerPricing
            );

            if (discountInfo.discountPercentage > 0) {
              const discountAmount =
                (basePrice * discountInfo.discountPercentage) / 100;
              finalPrice = Math.round(basePrice - discountAmount);
            }
          }

          // TODO: Add B2C discount calculation here in the future
          // Example: promotional discount, coupon code, etc.

          return {
            productId: product?._id,
            productName: product?.productName,
            variantId: el.variantId,
            variantName: variant?.name,
            originalPrice: variant?.price, // Always set original price
            discountedPrice:
              discountInfo.discountPercentage > 0
                ? { [currency]: finalPrice }
                : null, // Only set if discount applied
            quantity: el.quantity,
            image:
              variant?.image ||
              product?.productMedia.find((el) => el.type === "image"),
            stock: variant?.stock,
            discountPercentage: discountInfo.discountPercentage,
            subTotal: el.quantity * finalPrice,
            preOrder: product?.preOrder,
            moq: product?.moq,
            resellerPricing: product?.resellerPricing,
          };
        })
      );

      setFormData((prev) => ({
        ...prev,
        orderDetails: detailCartItem,
        totalAmount: detailCartItem.reduce(
          (sum: number, element: any) => sum + element.subTotal,
          0
        ),
        currency,
      }));
    } catch (error: any) {
      setError(error.message);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    // Only fetch cart items when session status is not "loading"
    if (status !== "loading") {
      fetchCartItem();
    }
  }, [currency, status]);

  if (isLoading) {
    return <LoadingPage />;
  }

  if (!isLoading && formData.orderDetails.length === 0) {
    return (
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-20">
        <div className="text-center">
          <div className="bg-gradient-to-r from-orange-400 to-rose-400 p-6 sm:p-8 rounded-full inline-flex mb-6 sm:mb-8">
            <ShoppingBag className="h-12 w-12 sm:h-16 sm:w-16 text-white" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-800 mb-3 sm:mb-4">
            Your Cart is Empty
          </h1>
          <p className="text-gray-600 mb-6 sm:mb-8 px-4">
            Looks like you haven't added any items to your cart yet.
          </p>
          <Link
            href="/catalog"
            className="inline-flex items-center px-4 sm:px-6 py-2 sm:py-3 bg-gradient-to-r from-orange-400 to-rose-400 text-white font-semibold rounded-lg hover:shadow-lg transform hover:scale-105 transition-all duration-200"
          >
            <ArrowLeft className="h-4 w-4 sm:h-5 sm:w-5 mr-2" />
            Continue Shopping
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-secondary min-h-screen">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 lg:gap-8">
          {/* Cart Items */}
          <div className="lg:col-span-2 space-y-6 lg:space-y-8">
            {/* Cart Items Section */}
            <div className="bg-white rounded-xl lg:rounded-2xl shadow-sm border border-primary/30 overflow-hidden">
              <div className="p-4 md:p-6">
                <div className="flex items-center space-x-3 mb-2">
                  <ShoppingBag className="w-6 h-6 text-primary" />
                  <h2 className="text-xl font-semibold text-gray-800">
                    Cart Items
                  </h2>
                </div>

                <div className="divide-y divide-gray-200">
                  {formData.orderDetails.map((item: any) => (
                    <div key={item.variantId} className="py-4">
                      {/* Desktop Cart Item - Full size for >= 750px */}
                      <div className="hidden min-[750px]:flex items-start space-x-4">
                        <img
                          src={item.image?.imageUrl}
                          alt={item.name}
                          className="w-30 h-30 object-cover rounded-lg"
                        />

                        <div className="flex-1 min-w-0">
                          <h3 className="text-lg font-semibold text-gray-800 mb-1">
                            {item.productName}
                          </h3>
                          <div className="flex items-center space-x-4 text-sm text-gray-600 mb-2">
                            Variant: {item.variantName}
                          </div>

                          {item.quantity > item.stock &&
                            item.preOrder.enabled && (
                              <div className="text-amber-500 text-sm font-medium">
                                Pre-Order
                              </div>
                            )}

                          <div className="flex items-center justify-between">
                            <div className="flex flex-col space-y-1">
                              {item.discountedPrice ? (
                                <>
                                  <div className="flex items-center space-x-2">
                                    <span className="text-lg font-bold text-orange-600">
                                      {format(item.discountedPrice[currency])}
                                    </span>
                                    <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full font-semibold">
                                      -{item.discountPercentage}%
                                    </span>
                                  </div>
                                  <span className="text-sm text-gray-500 line-through">
                                    {format(item.originalPrice[currency])}
                                  </span>
                                </>
                              ) : (
                                <span className="text-lg font-bold text-gray-800">
                                  {format(item.originalPrice[currency])}
                                </span>
                              )}
                            </div>

                            <div className="flex items-center space-x-3">
                              <div className="flex items-center border border-gray-300 rounded-lg">
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity - 1
                                    )
                                  }
                                  className="p-2 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={item.quantity === item.moq}
                                >
                                  <Minus className="h-4 w-4" />
                                </button>
                                <span className="px-4 py-2 font-medium">
                                  {item.quantity}
                                </span>
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity + 1
                                    )
                                  }
                                  className="p-2 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={
                                    item.quantity >= item.stock &&
                                    !item.preOrder.enabled
                                  }
                                >
                                  <Plus className="h-4 w-4" />
                                </button>
                              </div>

                              <button
                                onClick={() => removeItem(item.variantId)}
                                className="p-2 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors"
                              >
                                <Trash2 className="h-5 w-5" />
                              </button>
                            </div>
                          </div>
                          <div className="flex justify-between items-center mt-3 pt-2 border-t border-gray-100">
                            <span className="text-sm font-semibold text-gray-700">
                              Subtotal
                            </span>
                            <span className="text-lg font-bold text-primary">
                              {format(item.subTotal)}
                            </span>
                          </div>
                        </div>
                      </div>

                      {/* Compact Desktop Cart Item - For >= 490px && < 750px */}
                      <div className="hidden min-[490px]:max-[750px]:flex items-start space-x-3">
                        <img
                          src={item.image?.imageUrl}
                          alt={item.name}
                          className="w-25 h-25 object-cover rounded-lg"
                        />

                        <div className="flex-1 min-w-0">
                          <h3 className="text-base font-semibold text-gray-800 mb-1">
                            {item.productName}
                          </h3>
                          <div className="flex items-center space-x-3 text-xs text-gray-600 mb-2">
                            Variant: {item.variantName}
                          </div>

                          {item.quantity > item.stock &&
                            item.preOrder.enabled && (
                              <div className="text-amber-500 text-xs font-medium">
                                Pre-order
                              </div>
                            )}

                          <div className="flex items-center justify-between">
                            <div className="flex flex-col space-y-0.5">
                              {item.discountedPrice ? (
                                <>
                                  <div className="flex items-center space-x-1.5">
                                    <span className="text-base font-bold text-orange-600">
                                      {format(item.discountedPrice[currency])}
                                    </span>
                                    <span className="text-[10px] bg-green-100 text-green-700 px-1.5 py-0.5 rounded-full font-semibold">
                                      -{item.discountPercentage}%
                                    </span>
                                  </div>
                                  <span className="text-xs text-gray-500 line-through">
                                    {format(item.originalPrice[currency])}
                                  </span>
                                </>
                              ) : (
                                <span className="text-base font-bold text-gray-800">
                                  {format(item.originalPrice[currency])}
                                </span>
                              )}
                            </div>

                            <div className="flex items-center space-x-2">
                              <div className="flex items-center border border-gray-300 rounded-md">
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity - 1
                                    )
                                  }
                                  className="p-1 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={item.quantity === item.moq}
                                >
                                  <Minus className="h-3 w-3" />
                                </button>
                                <span className="px-2 py-1 font-medium text-sm">
                                  {item.quantity}
                                </span>
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity + 1
                                    )
                                  }
                                  className="p-1 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={
                                    item.quantity >= item.stock &&
                                    !item.preOrder.enabled
                                  }
                                >
                                  <Plus className="h-3 w-3" />
                                </button>
                              </div>

                              <button
                                onClick={() => removeItem(item.variantId)}
                                className="p-1 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-md transition-colors"
                              >
                                <Trash2 className="h-4 w-4" />
                              </button>
                            </div>
                          </div>

                          <div className="flex justify-between items-center mt-3 pt-2 border-t border-gray-100">
                            <span className="text-sm font-semibold text-gray-700">
                              Subtotal
                            </span>
                            <span className="text-base font-bold text-primary">
                              {format(item.subTotal)}
                            </span>
                          </div>
                        </div>
                      </div>

                      {/* Mobile Cart Item - Only show on screens <= 489px */}
                      <div className="block min-[490px]:hidden">
                        <div className="flex gap-3">
                          {/* Product Image */}
                          <div className="w-25 h-25 flex-shrink-0">
                            <img
                              src={item.image?.imageUrl}
                              alt={item.name}
                              className="w-full h-full object-cover rounded-lg"
                            />
                          </div>

                          {/* Product Info */}
                          <div className="flex-1 min-w-0 space-y-1">
                            {/* Product Name with overflow hidden */}
                            <h3 className="text-sm font-semibold text-gray-800 truncate">
                              {item.productName}
                            </h3>

                            {/* Variant Name with overflow hidden and smaller text */}
                            <div className="text-xs text-gray-600 truncate">
                              Variant: {item.variantName}
                            </div>

                            {/* Stock Status */}
                            {item.quantity > item.stock &&
                              item.preOrder.enabled && (
                                <span className="text-xs text-amber-500 font-medium">
                                  Pre-order
                                </span>
                              )}

                            {/* Price */}
                            <div className="flex flex-col space-y-0.5">
                              {item.discountedPrice ? (
                                <>
                                  <div className="flex items-center space-x-1.5">
                                    <span className="text-sm font-bold text-orange-600">
                                      {format(item.discountedPrice[currency])}
                                    </span>
                                    <span className="text-[9px] bg-green-100 text-green-700 px-1.5 py-0.5 rounded-full font-semibold">
                                      -{item.discountPercentage}%
                                    </span>
                                  </div>
                                  <span className="text-xs text-gray-500 line-through">
                                    {format(item.originalPrice[currency])}
                                  </span>
                                </>
                              ) : (
                                <span className="text-sm font-bold text-gray-800">
                                  {format(item.originalPrice[currency])}
                                </span>
                              )}
                            </div>

                            <div className="flex items-center space-x-2">
                              <span className="text-xs font-semibold text-gray-700">
                                Subtotal:
                              </span>
                              <span className="text-sm font-bold text-primary">
                                {format(item.subTotal)}
                              </span>
                            </div>

                            {/* Bottom Row: Quantity Controls and Delete Button */}
                            <div className="flex items-center justify-between pt-1">
                              <div className="flex items-center border border-gray-300 rounded-lg">
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity - 1
                                    )
                                  }
                                  className="p-1.5 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={item.quantity === item.moq}
                                >
                                  <Minus className="h-3 w-3" />
                                </button>
                                <span className="px-2 py-1.5 font-medium text-sm min-w-[32px] text-center">
                                  {item.quantity}
                                </span>
                                <button
                                  onClick={() =>
                                    updateQuantity(
                                      item.variantId,
                                      item.quantity + 1
                                    )
                                  }
                                  className="p-1.5 hover:bg-gray-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                  disabled={
                                    item.quantity >= item.stock &&
                                    !item.preOrder.enabled
                                  }
                                >
                                  <Plus className="h-3 w-3" />
                                </button>
                              </div>

                              <button
                                onClick={() => removeItem(item.variantId)}
                                className="p-1.5 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors"
                              >
                                <Trash2 className="h-4 w-4" />
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Shipping Address Section */}
            <div className="bg-white rounded-xl lg:rounded-2xl shadow-sm border border-primary/30">
              <div className="p-4 sm:p-6">
                <div className="flex items-center space-x-3 mb-6">
                  <MapPin className="w-6 h-6 text-primary" />
                  <h2 className="text-xl font-semibold text-gray-800">
                    Shipping Address
                  </h2>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="sm:col-span-2">
                    <div>
                      <label className="flex items-center space-x-2 text-sm font-medium text-gray-700 mb-2">
                        <User className="w-4 h-4" />
                        <span>Full Name</span>
                      </label>
                      <input
                        type="text"
                        value={formData.shippingAddress.fullName}
                        onChange={(e) =>
                          handleAddressChange("fullName", e.target.value)
                        }
                        className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                        placeholder="Enter your full name"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="flex items-center space-x-2 text-sm font-medium text-gray-700 mb-2">
                      <Mail className="w-4 h-4" />
                      <span>Email Address</span>
                    </label>
                    <input
                      type="email"
                      value={formData.shippingAddress.email}
                      onChange={(e) =>
                        handleAddressChange("email", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter your email"
                    />
                  </div>

                  <div>
                    <label className="flex items-center space-x-2 text-sm font-medium text-gray-700 mb-2">
                      <Phone className="w-4 h-4" />
                      <span>Phone Number</span>
                    </label>
                    <input
                      type="tel"
                      value={formData.shippingAddress.phone}
                      onChange={(e) =>
                        handleAddressChange("phone", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter your phone number"
                    />
                  </div>

                  <div>
                    <label className="flex items-center text-sm font-medium text-gray-700 mb-2">
                      <span>Country</span>
                    </label>
                    <input
                      type="text"
                      value={formData.shippingAddress.country}
                      onChange={(e) =>
                        handleAddressChange("country", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter your country"
                    />
                  </div>

                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      City
                    </label>
                    <input
                      type="text"
                      value={formData.shippingAddress.city}
                      onChange={(e) =>
                        handleAddressChange("city", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter your city"
                    />
                  </div>

                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      District
                    </label>
                    <input
                      type="text"
                      value={formData.shippingAddress.district}
                      onChange={(e) =>
                        handleAddressChange("district", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter district"
                    />
                  </div>

                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Zip Code
                    </label>
                    <input
                      type="text"
                      value={formData.shippingAddress.zipCode}
                      onChange={(e) =>
                        handleAddressChange("zipCode", e.target.value)
                      }
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors"
                      placeholder="Enter zip code"
                    />
                  </div>

                  <div className="sm:col-span-2">
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Street Address
                    </label>
                    <textarea
                      value={formData.shippingAddress.address}
                      onChange={(e) =>
                        handleAddressChange("address", e.target.value)
                      }
                      rows={3}
                      className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/80 focus:border-primary/80 transition-colors resize-none"
                      placeholder="Enter your complete address"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Order Summary */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-xl lg:rounded-2xl shadow-sm border border-primary/30 lg:sticky lg:top-30">
              <div className="p-4 sm:p-6">
                <h2 className="text-xl font-semibold text-gray-800 mb-6">
                  Order Summary
                </h2>

                <div className="space-y-4 mb-6">
                  <div className="flex justify-between text-gray-600">
                    <span>Subtotal</span>
                    <span>{format(totalAmount)}</span>
                  </div>

                  <div className="flex justify-between text-gray-600">
                    <span>Shipping</span>
                    <span>{format(shipping)}</span>
                  </div>

                  <div className="border-t border-gray-200 pt-4">
                    <div className="flex justify-between text-lg font-semibold text-gray-800">
                      <span>Total</span>
                      {format(total)}
                    </div>
                  </div>
                </div>

                <div className="space-y-2">
                  <button
                    className={`w-full font-semibold py-4 px-6 rounded-xl transition-all duration-200 shadow-lg ${
                      formData.orderDetails.length === 0 || !isAddressValid()
                        ? "bg-gray-300 text-gray-500 cursor-not-allowed"
                        : "bg-primary/90 hover:bg-primary text-white transform hover:scale-105 cursor-pointer"
                    }`}
                    disabled={
                      formData.orderDetails.length === 0 || !isAddressValid()
                    }
                    onClick={handleCheckout}
                  >
                    {!isAddressValid()
                      ? "Complete Address to Continue"
                      : "Confirm Order via Whatsapp"}
                  </button>
                  {isAddressValid() && (
                    <small>
                      <span className="text-red-500">* note:</span> you will be
                      directed to Whatsapp for secure and faster order
                      confirmation
                    </small>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
