import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavigationHeader from "@/components/navigation-header";
import { Footer } from "@/components/footer";
import { Providers } from "@/components/providers";
import FloatingButtonWA from "@/components/floating-button-wa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          <NavigationHeader />
          <main className="flex-grow">{children}</main>
          <FloatingButtonWA />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
